#!/bin/bash

COUNT=0

version() {
    case $1 in
        nodesource )
            echo `node -e 'console.log(require("./package.json").engines.nodesource)'`
            ;;

        * )
            echo `node -e 'console.log(require("./package.json").version)'`
            ;;
    esac
}

debug() {
    mkdir -p src/lang/locals

    cp ../lang/builds/* src/lang/locals/
    cp ../lang/countries.json src/lang/
    cp ../lang/emojis.json src/lang/

    ./node_modules/.bin/vue-cli-service serve --modern --mode development --port 49826
}

include() {
    if [[ -f "../repo/debian/pool/main/h/hoobs-gui/hoobs-gui_$2_$3.deb" ]]; then
        echo "$2-$3 already published"
    else
        reprepro -b ../repo/debian includedeb $1 builds/hoobs-gui-$2-hoobs-$3.deb
    fi
}

publish() {
    current=$(version)

    case $1 in
        stable )
            include "stable" "$current" "all"
            ;;

        edge )
            include "edge" "$current" "all"
            ;;

        bleeding )
            include "bleeding" "$current" "all"
            ;;

        list )
            list $2
            ;;
    esac
}

list() {
    case $1 in
        stable )
            reprepro -b ../repo/debian list stable hoobs-gui
            ;;

        edge )
            reprepro -b ../repo/debian list edge hoobs-gui
            ;;

        bleeding )
            reprepro -b ../repo/debian list bleeding hoobs-gui
            ;;

        * )
            reprepro -b ../repo/debian list stable hoobs-gui
            reprepro -b ../repo/debian list edge hoobs-gui
            reprepro -b ../repo/debian list bleeding hoobs-gui
            ;;
    esac
}

case $1 in
    version )
        shift

        version $@
        ;;

    lint )
        make lint
        ;;

    debug )
        debug
        ;;

    build )
        make gui
        ;;

    publish )
        shift

        publish $@
        ;;

    clean )
        make clean
        ;;
esac
